### ISSUE TITLE
What version of node can be used?

### ISSUE THREAD

**Issue by MichaelCastelbuono** [headless-ninja/hn-react-webform#15]
I'm trying to test the storybook and when I load http://localhost:6006/ I get the following error in the console:

![image](https://user-images.githubusercontent.com/385649/63800683-abab4780-c8dc-11e9-8923-814e51b4b67a.png)
Is the project dependent on a specific version of node?

**Edit**
I was on `master`. I tried checking out `v1.0.0` and got a little closer. But here's a new error I'm seeing:
![image](https://user-images.githubusercontent.com/385649/63801388-2f196880-c8de-11e9-8d16-e22274aeac7c.png)

**Comment by ianwensink** [comment]
@MichaelCastelbuono Thanks for your issue. I'm afraid the Storybooks are very outdated and the module itself has been deprecated as well.

Thank you for checking it out, though, please let me know if you need help with anything specific regarding Drupal webforms in React.

**Comment by ianwensink** [comment]
It does work and is being used in production in several apps, but I would recommend to not use this module. When we started out this project it made sense, but the Drupal Webform module has expanded greatly over the years, which made it tough to keep the module up to date. Everything that works out of the box (conditionals, lookups, validations) has to be redone in React. It's definitely possible, but it's tough.

The most important lesson out of this project was to stay away from rendering **anything** inside the module. When implementing it into different apps we always ran into issues when it came to changing the HTML structure and apply different styles.

If I'd rebuild it, I would use render props and such like to help to abstract all the logic into the module, but leave the rendering to the implementation.

I wouldn't say the module is a _very_ good starting point, but there could be some useful things in there, such as the mapper from Drupal Webform data to a React condition system. Other than that most of it has been made obsolete over the years.

Hope this helps.
